title: Senay F Tesfamichael
description: Personal Website
twitter_username: senayfre45
github_username: senay-dev
theme: jekyll-theme-cayman
# Get in Touch
<ul>
<li><a href="https://twitter.com/senayfre45">Twitter</a></li>
<li><a href="https://github.com/senay-dev">GitHub</a></li>
</ul>
